apiVersion: logstash.k8s.elastic.co/v1alpha1
kind: Logstash
metadata:
  name: elk
spec:
  count: 1
  elasticsearchRefs:
    - name: elk
  pipelines:
    - pipeline.id: main
      config.string: |
        input {
          beats {
            port => 5044
          }
        }
        output {
          elasticsearch {
            hosts => [ "http://elk-es-http:9200" ]
          }
        }
  services:
    - name: beats
      service:
        spec:
          ports:
            - name: "filebeat"
              port: 5044
              protocol: TCP
              targetPort: 5044
          type: ClusterIP
  version: 9.1.4
