apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: elk-es-http-tls
spec:
  commonName: elasticsearch.service.clee.private.morphacy.net
  dnsNames:
    - "elasticsearch.service.clee.private.morphacy.net"
    - "elasticsearch.service.chris-pc.clee.private.morphacy.net"
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: elk-es-http-tls
