apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: kube-state-metrics
spec:
  staticConfigs:
    - labels:
        app.kubernetes.io/name: prometheus
      targets:
        - kube-state-metrics.kube-system.svc.cluster.local:8080
