apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: monitoring-config

labels:
  - pairs:
      app: monitoring
      managedBy: argocd
      managementCodeGroup: chrismlee42
      managementCodeProject: monitoring-config

namespace: monitoring

resources:
  # Common namespace for all monitoring components
  - namespace.yaml
  # ELK Stack
  # - elk-elasticsearch-httproute.yaml
  - elk-elasticsearch.yaml
  - elk-es-http-tls-secret.yaml
  - elk-kb-https-tls-secret.yaml
  # - elk-kibana-httproute.yaml
  - elk-kibana.yaml
  - elk-logstash-beats-httproute.yaml
  - elk-logstash.yaml
  # Grafana
  - grafana-grafana.yaml
  - grafana-httproute.yaml
  #- k8s-cluster-summary-grafanadashboard.yaml
  #- k8s-dashboard-grafanadashboard.yaml
  - kube-state-metrics-scrapeconfig.yaml
  - kube-state-metrics-servicemonitor.yaml
  # Node Exporter
  - node-exporter-daemonset.yaml
  - node-exporter-full-grafanadashboard.yaml
  - node-exporter-networkpolicy.yaml
  - node-exporter-scrapeconfig.yaml
  - node-exporter-service.yaml
  - node-exporter-servicemonitor.yaml
  # Prometheus
  - prometheus-clusterrole.yaml
  - prometheus-clusterrolebinding.yaml
  - prometheus-grafanadatasource.yaml
  - prometheus-httproute.yaml
  - prometheus-prometheus.yaml
  - prometheus-scrapeconfig.yaml
  - prometheus-servicemonitor.yaml
  - prometheus-serviceaccount.yaml
  # Cert-Manager Self-Signed CA Trust Bundle
  - trust-bundle.yaml
