apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: monitoring-config

labels:
  - pairs:
      app: monitoring
      managedBy: argocd
      managementCodeGroup: chrismlee42-dev
      managementCodeProject: monitoring-config

namespace: monitoring

resources:
  - namespace.yaml
  - node-exporter-daemonset.yaml
  - node-exporter-scrapeconfig.yaml
  - node-exporter-service.yaml
  - node-exporter-servicemonitor.yaml
  - prometheus-clusterrole.yaml
  - prometheus-clusterrolebinding.yaml
  - prometheus-httproute.yaml
  - prometheus-prometheus.yaml
  - prometheus-serviceaccount.yaml
