apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: monitoring-config

commonAnnotations:
  "helm.sh/resource-policy": keep

commonLabels:
  app: monitoring
  managedBy: argocd
  managementCodeGroup: chrismlee42-dev
  managementCodeProject: monitoring-config

namespace: monitoring

resources:
  # Determine latest stable version from https://github.com/prometheus-operator/prometheus-operator/releases
  # - https://github.com/prometheus-operator/prometheus-operator/releases/download/v0.84.1/bundle.yaml
  - namespace.yaml
  - prometheus-clusterrole.yaml
  - prometheus-clusterrolebinding.yaml
  - prometheus-prometheus.yaml
  - prometheus-serviceaccount.yaml
