apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: node-exporter
  labels:
    service-monitor: node-exporter
spec:
  jobLabel: service-monitor
  selector:
    matchLabels:
      service-monitor: node-exporter
  namespaceSelector:
    matchNames:
    - monitoring
  endpoints:
  - port: http-metrics
    interval: 30s
