apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: node-exporter
spec:
  instanceSelector:
    matchLabels:
      dashboards: "grafana"
  datasource:
    name: node-exporter
    type: prometheus
    access: proxy
    url: http://node-exporter:9100
    isDefault: false
    jsonData:
      'tlsSkipVerify': true
      'timeInterval': "5s"
