apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: trust
spec:
  sources:
  - secret:
      name: "self-signed-ca"
      key: "tls.crt"
  target:
    configMap:
      key: "ca.crt"
